pool:
  name: DenemeLocalPool
  demands: maven

resources:
  repositories:
  - repository: main
    type: github
    name: eminturan/denemeproject
    trigger:
      branches:
        include:
        - main
    endpoint: eminturan

  - repository: templates
    type: github
    name: eminturan/azure-templates
    endpoint: eminturan

#Your build pipeline references an undefined variable named ‘Parameters.mavenPOMFile’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

variables:
- name: namespace
  value: deneme-dev
- name: app_name
  value: denemeproject
- name: helm_path
  value: backend-api-0.1.0.tgz
- name: project_env
  value: dev
- name: toolset
  value: 'maven'

stages:
- stage: CodeBuildStage
  displayName: Code Build Stage
  jobs:
  - job: Code_Build_Job
    displayName: Code Build Job
    steps:
      - checkout: templates
      - checkout: main
      - template: ./code-build.yml@templates
        parameters:
           workingDirectory: '$(Build.Repository.LocalPath)/$(variables.app_name)'
           toolset: ${{ variables.toolset }}
