pool:
  name: DenemeLocalPool

resources:
  repositories:
  - repository: main
    type: github
    name: eminturan/denemeproject
    trigger:
      branches:
        include:
        - main
    endpoint: eminturan

  - repository: templates
    type: github
    name: eminturan/azure-templates
    endpoint: eminturan

#Your build pipeline references an undefined variable named ‘Parameters.mavenPOMFile’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972

variables:
- name: namespace
  value: deneme-dev
- name: app_name
  value: 'deneme-project'
- name: helm_path
  value: backend-api-0.1.0.tgz
- name: project_env
  value: dev
- name: toolset
  value: 'maven'
- name: repo_name
  value: denemeproject
- name: registry_url
  value: 'eminturan'
- name: working_path
  value: '$(Build.Repository.LocalPath)/${{ variables.repo_name }}'
#  value: '$(Build.SourcesDirectory)/${{ variables.repo_name }}'

stages:
- stage: CodeBuildStage
  displayName: Code Build Stage
  jobs:
  - job: CodeBuildJob
    pool:
      name: DenemeLocalPool
    displayName: Code Build Job
    steps:
      - checkout: templates
      - checkout: main
      - template: ./code-build.yml@templates
        parameters:
           workingDirectory: '${{ variables.working_path }}'
           toolset: ${{ variables.toolset }}
  - job: DockerBuildJob
    pool:
      name: DenemeLocalPool
    displayName: Docker Build Job
    steps:
      - template: ./docker-build.yml@templates
        parameters:
           workingDirectory: '${{ variables.working_path }}'
           registry_url: '${{ variables.registry_url }}'
           image_name: '${{ variables.app_name }}'


#- stage: DockerBuildStage
#  displayName: Docker Build Stage
#  jobs:
#  - job: Docker_Build_Job
#    displayName: Docker Build Job
#    steps:
#      - template: ./docker-build.yml@templates
#        parameters:
#           registry_url: '${{ variables.registry_url }}'
#           image_name: '${{ variables.app_name }}'
